name = "cloudpaste"
main = "src/index.js"
compatibility_date = "2024-01-09"

[vars]
ENVIRONMENT = "development"
TOTAL_STORAGE_GB = "6"  # 总存储容量，单位GB
ADMIN_USERNAME = "admin"  # 管理员用户名
ADMIN_PASSWORD = "admin"  # 管理员密码
MAX_FILE_SIZE = "500"  # 单个文件大小限制，单位MB，Workers上传到R2的限制是500MB
SESSION_DURATION = "7d"  # 会话持续时间，支持：1h,1d,7d,30d
TEXT_UPLOAD_ENABLED = "true"  # 文本上传开关，默认开启
FILE_UPLOAD_ENABLED = "true"  # 文件上传开关，默认开启

[[kv_namespaces]]
binding = "CLOUDPASTE_KV"
id = "your-kv-id"
preview_id = "your-preview-kv-id"

[[r2_buckets]]
binding = "CLOUDPASTE_BUCKET"
bucket_name = "cloudpaste"
preview_bucket_name = "cloudpaste-dev"

[site]
bucket = "./public"